export const legalContent: Record<string, {
  title: string;
  lastUpdated: string;
  sections: Array<{
    title?: string;
    content: string[];
  }>;
}> = {
  terms: {
    title: 'Terms of Service',
    lastUpdated: 'March 15, 2024',
    sections: [
      {
        title: '1. Acceptance of Terms',
        content: [
          'By accessing and using this website and our services, you accept and agree to be bound by the terms and provision of this agreement.',
          'Please read these terms carefully before using our services. If you do not agree to all of these terms, you may not use our services.'
        ]
      },
      {
        title: '2. Description of Service',
        content: [
          'We provide AI-powered content generation and marketing automation services.',
          'We reserve the right to modify, suspend, or discontinue any part of the service at any time.'
        ]
      },
      {
        title: '3. User Obligations',
        content: [
          'You agree to use our services only for lawful purposes and in accordance with these terms.',
          'You are responsible for maintaining the confidentiality of your account information.'
        ]
      }
    ]
  },
  privacy: {
    title: 'Privacy Policy',
    lastUpdated: 'March 15, 2024',
    sections: [
      {
        title: '1. Information We Collect',
        content: [
          'We collect information that you provide directly to us when using our services.',
          'This may include your name, email address, and any other information you choose to provide.'
        ]
      },
      {
        title: '2. How We Use Your Information',
        content: [
          'We use the information we collect to provide, maintain, and improve our services.',
          'We may use your email address to send you service-related notices and promotional messages.'
        ]
      },
      {
        title: '3. Information Sharing',
        content: [
          'We do not share your personal information with third parties except as described in this policy.',
          'We may share your information in response to legal requests or to protect our rights.'
        ]
      }
    ]
  },
  disclaimer: {
    title: 'Disclaimer',
    lastUpdated: 'March 15, 2024',
    sections: [
      {
        content: [
          'The information provided by our service is for general informational purposes only.',
          'We make no representations or warranties of any kind, express or implied, about the completeness, accuracy, reliability, suitability, or availability of our service.'
        ]
      },
      {
        title: 'Generated Content',
        content: [
          'The content generated by our AI service is provided "as is" without any guarantees.',
          'Users are responsible for reviewing and verifying all generated content before use.'
        ]
      },
      {
        title: 'Limitation of Liability',
        content: [
          'We shall not be liable for any indirect, incidental, special, consequential, or punitive damages resulting from your use of our services.',
          'Your use of our service is at your own risk.'
        ]
      }
    ]
  },
  cookie: {
    title: 'Cookie Policy',
    lastUpdated: 'March 15, 2024',
    sections: [
      {
        title: 'What Are Cookies',
        content: [
          'Cookies are small text files that are placed on your device when you visit our website.',
          'They help us provide you with a better experience by remembering your preferences and understanding how you use our service.'
        ]
      },
      {
        title: 'How We Use Cookies',
        content: [
          'We use cookies to understand how you interact with our website and to improve our services.',
          'Some cookies are essential for the operation of our website, while others help us improve your experience.'
        ]
      },
      {
        title: 'Your Cookie Choices',
        content: [
          'You can control and/or delete cookies as you wish.',
          'You can delete all cookies that are already on your computer and you can set most browsers to prevent them from being placed.'
        ]
      }
    ]
  },
  'acceptable-use': {
    title: 'Acceptable Use Policy',
    lastUpdated: 'March 15, 2024',
    sections: [
      {
        title: 'Prohibited Uses',
        content: [
          'You may not use our service for any unlawful purpose or in any way that could damage, disable, overburden, or impair our service.',
          'You may not attempt to gain unauthorized access to any part of our service or any systems or networks connected to our service.'
        ]
      },
      {
        title: 'Content Guidelines',
        content: [
          'You agree not to generate or distribute content that is unlawful, harmful, threatening, abusive, harassing, defamatory, or otherwise objectionable.',
          'You are responsible for ensuring that any content generated through our service complies with applicable laws and regulations.'
        ]
      },
      {
        title: 'Enforcement',
        content: [
          'We reserve the right to investigate and take appropriate legal action against anyone who violates these terms.',
          'We may terminate or suspend your access to our service immediately, without prior notice or liability.'
        ]
      }
    ]
  }
};